# check for updates at: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tap-new.rb
name: brew test-bot
on:
  push:
    branches:
      - main
#   pull_request:
#     types:
#       - opened
#       - synchronize
#       - edited
jobs:
  test-bot:
    runs-on: macos-13
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.GH_PAT }}
          debug: true

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
          
      - run: brew update
      - run: brew test-bot --only-tap-syntax
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}

      - run: |
          git config --global http.extraheader "Authorization: Basic $(echo -n "x-access-token:${{ secrets.GH_PAT }}" | base64 | tr -d '\n')"
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}

      - run: |
          git ls-remote 'https://github.com/dummy-andra/getargv.git'
          git ls-remote 'https://github.com/dummy-andra/homebrew-tap.git'

      - name: Brew Test-Bot (Debug)
        run: brew test-bot  --root-url=https://ghcr.io/v2/dummy-andra/homebrew-tap
        #if: github.event_name == 'pull_request'
        env:
          ACTIONS_STEP_DEBUG: true
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}


      - name: Upload bottles as an artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: bottles
          path: '*.bottle.*'

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["pr-pull"]
            })
